Added RBAC unit tests for clone action API
StackStorm/st2-rbac-backend pull request #61
Opened 2021-10-08 13:45 UTC by ankita-orchestral

For action clone API, RBAC unit tests for following scenarios are added:
* ACTION_VIEW permission on source action
* ACTION_CREATE permission on destination action if destination action doesn't exist
* ACTION_CREATE permission on destination action if destination action exists
* ACTION_DELETE permission on destination action in case of action clone overwrite

2021-10-08 13:52 UTC, ankita-orchestral commented
https://github.com/StackStorm/st2/pull/5345 #

2021-10-20 06:31 UTC, mahesh-orch commented
@m4dcoder I have refactored unit tests as per your suggested changes. Please review.

2021-12-10 17:44 UTC, m4dcoder requested changes

2021-12-10 17:44 UTC, m4dcoder commented on tests/unit/controllers/api/v1/test_actions_rbac.py
> +        self.assertEqual(clone_resp.status_code, http_client.CREATED)
Can we do a check herer that the overwritten ACTION_3 is in fact a clone of ACTION_2?

2021-12-10 17:44 UTC, m4dcoder commented on tests/unit/controllers/api/v1/test_actions_rbac.py
> +        expected_msg = ('User "no_permissions" doesn\'t have required permission '
Please use string formatting to pass in user name instead of hard coding "no_permissions".

2021-12-10 17:44 UTC, m4dcoder commented on tests/unit/controllers/api/v1/test_actions_rbac.py
> +        expected_msg = ('User "no_create_permission" doesn\'t have required '
Please use string formatting to pass in user name instead of hard coding "no_create_permission".

2021-12-10 17:44 UTC, m4dcoder commented on tests/unit/controllers/api/v1/test_actions_rbac.py
> +        expected_msg = ('User "no_create_permission" doesn\'t have required '
Please use string formatting to pass in user name instead of hard coding "no_create_permission".

2021-12-10 17:44 UTC, m4dcoder commented on tests/unit/controllers/api/v1/test_actions_rbac.py
> +        expected_msg = ('User "no_delete_permission" doesn\'t have required '
Please use string formatting to pass in user name instead of hard coding "no_delete_permission".

2021-12-10 17:50 UTC, m4dcoder requested changes
Can you also fix the CI jobs so they are not failing here?

2021-12-13 17:56 UTC, m4dcoder approved these changes

2021-12-13 17:56 UTC, merged